// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnYyKEmuDu6nEOFHQzfHZfZ9wvwazB8VE',
    appId: '1:694864445298:web:9a91fc1c47f8e95140a7eb',
    messagingSenderId: '694864445298',
    projectId: 'food-runner-project-mad',
    authDomain: 'food-runner-project-mad.firebaseapp.com',
    storageBucket: 'food-runner-project-mad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj_6fQsFQV6Rb-zhs0DtR66oWP-GlaB_8',
    appId: '1:694864445298:android:9d2b40038454223a40a7eb',
    messagingSenderId: '694864445298',
    projectId: 'food-runner-project-mad',
    storageBucket: 'food-runner-project-mad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHBgPEnMV3l8s-i6bKFdt47AZnDNdJg0o',
    appId: '1:694864445298:ios:6701a6fcbee179d440a7eb',
    messagingSenderId: '694864445298',
    projectId: 'food-runner-project-mad',
    storageBucket: 'food-runner-project-mad.firebasestorage.app',
    iosBundleId: 'com.example.act1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHBgPEnMV3l8s-i6bKFdt47AZnDNdJg0o',
    appId: '1:694864445298:ios:6701a6fcbee179d440a7eb',
    messagingSenderId: '694864445298',
    projectId: 'food-runner-project-mad',
    storageBucket: 'food-runner-project-mad.firebasestorage.app',
    iosBundleId: 'com.example.act1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnYyKEmuDu6nEOFHQzfHZfZ9wvwazB8VE',
    appId: '1:694864445298:web:510b68d37547c24940a7eb',
    messagingSenderId: '694864445298',
    projectId: 'food-runner-project-mad',
    authDomain: 'food-runner-project-mad.firebaseapp.com',
    storageBucket: 'food-runner-project-mad.firebasestorage.app',
  );
}
